### ISSUE TITLE
fatal: Could not read from remote repository

### ISSUE THREAD

**Issue by voztovoice** [OpenSIPS/opensips-softswitch-ce#1]
Command:

git clone --recursive https://github.com/OpenSIPS/opensips-softswitch-ce.git

Result:

Submodule 'etc/opensips' (git@github.com:OpenSIPS/opensips-softswitch-ce-config.git) registered for path 'etc/opensips'
Cloning into '/usr/src/opensips-softswitch-ce/etc/opensips'...
The authenticity of host 'github.com (140.82.113.4)' can't be established.
ED25519 key fingerprint is SHA256:+DiY3wvvV6TuJJhbpZisF/zLDA0zPMSvHdkr4UvCOqU.
This key is not known by any other names
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added 'github.com' (ED25519) to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:OpenSIPS/opensips-softswitch-ce-config.git' into submodule path '/usr/src/opensips-softswitch-ce/etc/opensips' failed
Failed to clone 'etc/opensips'. Retry scheduled
Cloning into '/usr/src/opensips-softswitch-ce/etc/opensips'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

**Comment by dariusstefan** [comment]
Hello! I just changed the url to the one that uses https. Should work now
